// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARMCwkM6Acv0BFNH8x0U7BzCe0kdgIuq4',
    appId: '1:800363096013:web:2125c0555b0095da70c684',
    messagingSenderId: '800363096013',
    projectId: 'flutter-app-2aab5',
    authDomain: 'flutter-app-2aab5.firebaseapp.com',
    storageBucket: 'flutter-app-2aab5.appspot.com',
    measurementId: 'G-Q9KPP0M467',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Chb0x85dKM9ngf7MjGrX-X06QTTc1wE',
    appId: '1:800363096013:android:5ceab1da1b8fee1970c684',
    messagingSenderId: '800363096013',
    projectId: 'flutter-app-2aab5',
    storageBucket: 'flutter-app-2aab5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRKwTqqIoq5uOj5Fvh1ppJsW_4xPFVKQ0',
    appId: '1:800363096013:ios:259f2ba7e586932370c684',
    messagingSenderId: '800363096013',
    projectId: 'flutter-app-2aab5',
    storageBucket: 'flutter-app-2aab5.appspot.com',
    iosClientId: '800363096013-vv1fcrs4pomljrpcmlup1shdq033p5nm.apps.googleusercontent.com',
    iosBundleId: 'com.example.demofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRKwTqqIoq5uOj5Fvh1ppJsW_4xPFVKQ0',
    appId: '1:800363096013:ios:0d7f058bcab32e6670c684',
    messagingSenderId: '800363096013',
    projectId: 'flutter-app-2aab5',
    storageBucket: 'flutter-app-2aab5.appspot.com',
    iosClientId: '800363096013-oadqrieqi1vo57bfk26k1auc0sjekaal.apps.googleusercontent.com',
    iosBundleId: 'com.example.demofirebase.RunnerTests',
  );
}
