// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5e7S9Vd402s5g274PSv8GzNR-vKCT470',
    appId: '1:340613270382:web:2c227d955b666688374f7f',
    messagingSenderId: '340613270382',
    projectId: 'fir-crud-4d3f1',
    authDomain: 'fir-crud-4d3f1.firebaseapp.com',
    storageBucket: 'fir-crud-4d3f1.appspot.com',
    measurementId: 'G-4K60MF2LHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3vyS7U22hOFfe-stChNojWPgWb1C3rO0',
    appId: '1:340613270382:android:84ef6bf9edaf1267374f7f',
    messagingSenderId: '340613270382',
    projectId: 'fir-crud-4d3f1',
    storageBucket: 'fir-crud-4d3f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOH_PotbUHMBQPpPszaZsKpAPL5BXmpVM',
    appId: '1:340613270382:ios:0734c6fe2a51ef27374f7f',
    messagingSenderId: '340613270382',
    projectId: 'fir-crud-4d3f1',
    storageBucket: 'fir-crud-4d3f1.appspot.com',
    iosClientId: '340613270382-f4884t6dkvrrofl5mebiq6hfcnlfreu1.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOH_PotbUHMBQPpPszaZsKpAPL5BXmpVM',
    appId: '1:340613270382:ios:f7386193a4ac699d374f7f',
    messagingSenderId: '340613270382',
    projectId: 'fir-crud-4d3f1',
    storageBucket: 'fir-crud-4d3f1.appspot.com',
    iosClientId: '340613270382-sjnf4koqspbo9e46k0bq2b4ai66d4j2g.apps.googleusercontent.com',
    iosBundleId: 'pe.edu.upeu.asistenciaApp.RunnerTests',
  );
}
